DROP TABLE IF EXISTS windows;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS sensors;

-- Create the sensors table
CREATE TABLE IF NOT EXISTS sensors (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    sensor_value FLOAT NOT NULL,
    sensor_type VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
    );

-- Insert sample data into the sensors table
INSERT INTO sensors (id, name, sensor_value, sensor_type) VALUES (1, 'Temperature Sensor', 25.0, 'TEMPERATURE');
INSERT INTO sensors (id, name, sensor_value, sensor_type) VALUES (2, 'Humidity Sensor', 45.0, 'HUMIDITY');
INSERT INTO sensors (id, name, sensor_value, sensor_type) VALUES (3, 'Pressure Sensor', 1020.0, 'PRESSURE');

-- Create the rooms table
CREATE TABLE IF NOT EXISTS rooms (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY,
name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
    );

-- Insert sample data into the rooms table
INSERT INTO rooms (id, name) VALUES (1, 'Living Room');
INSERT INTO rooms (id, name) VALUES (2, 'Bedroom');
INSERT INTO rooms (id, name) VALUES (3, 'Office');

-- Create the windows table
CREATE TABLE IF NOT EXISTS windows (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY,
 name VARCHAR(255) NOT NULL,
    window_status VARCHAR(255) NOT NULL,
    room_id BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE
    );

-- Insert sample data into the windows table
INSERT INTO windows (id, name, window_status, room_id) VALUES (1, 'Main Window', 'OPEN', 1);
INSERT INTO windows (id, name, window_status, room_id) VALUES (2, 'Side Window', 'CLOSED', 1);
INSERT INTO windows (id, name, window_status, room_id) VALUES (3, 'Bedroom Window', 'LOCKED', 2);